language: node_js
node_js:
  - node
  - iojs
  - "4"
  - "3"
  - "2"
  - "1.8"
  - "1.0"
  - "0.12"
  - "0.11"
script:
  - npm run cover
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
