ui: mocha-tdd
browsers:
  - name: chrome
    version: 42..latest
  - name: firefox
    version: 40..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 7..latest
  - name: microsoftedge
    version: 20..latest
  - name: opera
    version: 8..latest
  - name: android
    version: 5..latest
