ui: mocha-tdd
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: 6..latest
  - name: ie
    version: 11..latest
  - name: microsoftedge
    version: 13..latest
  - name: android
    version: 4.4..latest
  - name: iphone
    version: latest
