ui: mocha-tdd
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: [6, 7, 8, 9..latest]
  - name: ie
    version: 11..latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: 11..latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest
browserify:
  - add:
      - etc/browser/_shim.js
