ui: mocha-tdd
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: 6..latest
  - name: ie
    version: 11..latest
  - name: microsoftedge
    version: 20..latest
  - name: opera
    version: 11..latest
  - name: android
    version: latest
